<?php
namespace App\Http\Controllers;
use App\Models\{Feedback,GalleryItem,Package,PageVisit,Service};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{Auth,Storage};
use Illuminate\Support\Str;
class AdminController extends Controller {
 public function login(){return view('admin.login');}
 public function authenticate(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required']);if(Auth::attempt($d,$r->boolean('remember'))){$r->session()->regenerate();return redirect()->route('admin.dashboard');}return back()->withErrors(['email'=>'Invalid email or password.'])->onlyInput('email');}
 public function logout(Request $r){Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return redirect()->route('admin.login');}
 public function dashboard(){ $today=now()->startOfDay(); $start=now()->subDays(6)->startOfDay(); $daily=PageVisit::where('created_at','>=',$start)->selectRaw('DATE(created_at) as day, count(*) as visits')->groupBy('day')->pluck('visits','day'); $series=collect(range(6,0))->map(function($days) use($daily){$date=now()->subDays($days);return ['label'=>$date->format('D'),'date'=>$date->toDateString(),'visits'=>(int)($daily[$date->toDateString()]??0)];}); return view('admin.dashboard',['counts'=>['services'=>Service::count(),'packages'=>Package::count(),'gallery'=>GalleryItem::count(),'feedback'=>Feedback::where('status','new')->count()],'visits'=>['total'=>PageVisit::count(),'today'=>PageVisit::where('created_at','>=',$today)->count(),'unique'=>PageVisit::whereNotNull('visitor_hash')->distinct('visitor_hash')->count('visitor_hash'),'pages'=>PageVisit::selectRaw('path, count(*) as visits')->groupBy('path')->orderByDesc('visits')->limit(5)->get(),'recent'=>PageVisit::latest()->limit(6)->get(),'series'=>$series]]);}
 public function resources(string $type){return view('admin.resources',['type'=>$type,'items'=>$this->model($type)::latest()->get()]);}
 public function edit(string $type,?int $id=null){return view('admin.form',['type'=>$type,'item'=>$id?$this->model($type)::findOrFail($id):null]);}
 public function save(Request $r,string $type,?int $id=null){$model=$this->model($type);$item=$id?$model::findOrFail($id):new $model;$data=$this->validated($r,$type);foreach(['image','before_image'] as $field){if($r->hasFile($field)){if($item->$field)Storage::disk('public')->delete($item->$field);$data[$field]=$r->file($field)->store($type==='gallery'?'gallery':$type,'public');}}if(in_array($type,['services','packages']))$data['features']=array_values(array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',$r->input('features_text','')))));if($type==='packages'&&!$item->exists)$data['slug']=Str::slug($data['title']).'-'.str()->lower(str()->random(5));$item->fill($data)->save();return redirect()->route('admin.resources',$type)->with('success',ucfirst($type).' saved.');}
 public function delete(string $type,int $id){$item=$this->model($type)::findOrFail($id);foreach(['image','before_image'] as $field)if($item->$field)Storage::disk('public')->delete($item->$field);$item->delete();return back()->with('success','Item deleted.');}
 public function feedback(){return view('admin.feedback',['items'=>Feedback::latest()->get()]);}
 public function updateFeedback(Request $r,Feedback $feedback){$data=$r->validate(['status'=>'required|in:new,read,resolved,published','admin_notes'=>'nullable|string|max:3000','role'=>'nullable|string|max:100','rating'=>'nullable|integer|min:1|max:5','result'=>'nullable|string|max:200','message'=>'nullable|string|max:3000','is_published'=>'nullable|boolean']);$data['is_published']=$r->boolean('is_published');$feedback->update($data);return back()->with('success','Feedback updated.');}
 private function model(string $type):string{return match($type){'services'=>Service::class,'packages'=>Package::class,'gallery'=>GalleryItem::class,default=>abort(404)};}
 private function validated(Request $r,string $type):array{$rules=['title'=>'nullable|string|max:150','description'=>'nullable|string|max:3000','is_published'=>'nullable|boolean','image'=>'nullable|image|max:5120'];if($type==='services')$rules+=['title'=>'required|string|max:150','description'=>'required|string|max:3000','icon'=>'nullable|string|max:50'];if($type==='packages')$rules+=['title'=>'required|string|max:150','duration'=>'required|string|max:150','price'=>'required|string|max:80','description'=>'required|string|max:3000'];if($type==='gallery')$rules+=['before_image'=>'nullable|image|max:5120','category'=>'required|in:training,transformation'];$data=$r->validate($rules);$data['is_published']=$r->boolean('is_published');return $data;}
}
